name: Update OpenWrt Packages
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: 0 */12 * * *

env:
  TZ: Asia/Shanghai

jobs:
  Update_OpenWrt_Packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Python 3.9.x
        uses: actions/setup-python@main
        with:
          python-version: '3.9.x'

      - name: Install Dependencies
        run: |
          sudo timedatectl set-timezone "$TZ"
          python -m pip install --upgrade pip
          pip install -U GitPython

      - name: Update OpenWrt Packages
        id: update
        run: |
          python packages.py
          rm -rf __pycache__
          echo "message=$(date)" >> $GITHUB_OUTPUT

      - name: Commit
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          status=$(git status -sb)
          if [ "$status" == "## main...origin/main" ];then
              echo "nothing to commit, working tree clean"
          else
          Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🛸" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
          git add .
          git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(TZ='Asia/Shanghai' date +%Y-%m-%d" "%H:%M:%S)${Emoji[$[$RANDOM % ${#Emoji[@]}]]}"
          fi
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main      
          
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 2
