name: Update OpenWrt Packages
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  Update_OpenWrt_Packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python 3.9.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U GitPython

      - name: Update OpenWrt Packages
        id: update
        run: |
          python packages.py
          rm -rf __pycache__
          echo "message=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update packages: ${{ steps.update.outputs.message }}"
          branch: main
          # 关键参数：禁用标签创建
          create_tag: false  # 默认是 true
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          token: ${{ secrets.GH_TOKEN }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.0
        with:
          retain_days: 0
          keep_minimum_runs: 2
          token: ${{ secrets.GH_TOKEN }}
