name: Update OpenWrt Packages
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  Update_OpenWrt_Packages:
    runs-on: ubuntu-latest

    permissions:  # 关键权限声明
      contents: write
      actions: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # 深度克隆确保分支关联
          fetch-depth: 0  
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U GitPython

      - name: Update Packages
        id: update
        run: |
          python packages.py
          rm -rf __pycache__
          echo "message=$(date +'%Y-%m-%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Configure Git Identity
        run: |  # 强制设置全局Git身份
          git config --global user.name "OpenWrt Package Bot"
          git config --global user.email "openwrt-bot@noreply.github.com"

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update ${{ steps.update.outputs.message }}"
          branch: main
          create_tag: false  # 彻底禁用标签
          # 使用PAT替代默认token（需在仓库Secrets创建PAT）
          token: ${{ secrets.GH_TOKEN }}  
          commit_options: "--no-verify"  # 跳过pre-commit检查
          add_options: "-u"  # 强制添加所有修改

      - name: Cleanup
        run: git reset --hard HEAD  # 确保工作区干净

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.0
        with:
          retain_days: 0
          keep_minimum_runs: 2
          token: ${{ secrets.GH_TOKEN }}
